"""add created_by_id to meetings

Revision ID: d49673a371fb
Revises: 24989ab3e779
Create Date: 2026-08-14 08:59:30.438769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49673a371fb'
down_revision: Union[str, Sequence[str], None] = '24989ab3e779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite cannot ALTER TABLE ADD CONSTRAINT, so the foreign key is added via
    # batch mode (table recreation) rather than the plain autogenerated ops.
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_meetings_created_by_id'), ['created_by_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_meetings_created_by_id_users', 'users', ['created_by_id'], ['id']
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_created_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meetings_created_by_id'))
        batch_op.drop_column('created_by_id')
